apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ros-project-gitops
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/rosadsky/ros-project-gitops