apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/part-of: ros-project
    app.kubernetes.io/name: ros-project

namespace: ros-project

resources:
- cd.kustomization.yaml
- install.kustomization.yaml
- git-repository.yaml