apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ros-project-content
spec:
  microFrontend: ros-project
  element: hospital-dashboard
  attributes:
    - name: base-path
      value: /ros-project/
    - name: api-base
      value: /ros-project-api/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ros-project(/.*)?$"