apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ros-project-content
spec:
  microFrontend: ros-project
  element: ros-project-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ros-project(/.*)?$"