apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ros-ambulance-ufe-content
spec:
  microFrontend: ros-ambulance-ufe
  element: ros-ambulance-wl-app
  attributes:
    - name: base-path
      value: /ros-project/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ros-project(/.*)?$"