api: apps/v1
kind: Deployment
metadata:
  name: ros-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /ros-openapi
            - name: BASE_URL
              value: /ros-openapi-ui